### ISSUE TITLE
Legacy grants no longer available to new customers?

### ISSUE THREAD

**Issue by jngexact** [auth0/Auth0.WinformsWPF#30]
It appears if we are setting up a new account (with a new client), the legacy RO grant type is not available. I've tried adding Password and Password-Realm grants to the client, but every time I try to acquire a token with the library for this client, I get 

{ "error": "unauthorized_client",
"error_description": "Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client." }

Does this mean new accounts can no longer use this library???

**Comment by jerriep** [comment]
Please see the following document on how to enable the legacy grant types for your Client:
https://auth0.com/docs/clients/client-grant-types

Also, I would suggest you start looking into replacing the use of this library with the new OIDC Client library. More information can be found in the Winforms/WPF quickstart:
https://auth0.com/docs/quickstart/native/wpf-winforms

**Comment by jngexact** [comment]
I have tried adding http://auth0.com/oauth/legacy/grant-type/ro received the error that legacy grant types is not available for my client. 

Does this mean this client (which was recently created with an account I just created) cannot use this library?

**Comment by jerriep** [comment]
Yes, as noted in that document:

> As of 8 June 2017, new Auth0 customers cannot add any of the legacy grant types to their Clients. Only customers as of 8 June 2017 can add legacy grant types to their existing Clients.

Please use the new OIDC Client as described in the Quickstart I linked above.

One more thing to note is that the legacy RO endpoint is replaced with the new Resource Owner Password endpoint (https://auth0.com/docs/api/authentication#resource-owner-password)

So instead of using the OIDC Client you can call that endpoint directly by making use of the Auth0 Authentication API NuGet package (https://www.nuget.org/packages/Auth0.AuthenticationApi). The code for that will look something like the following:

```csharp
using Auth0.AuthenticationApi;
using Auth0.AuthenticationApi.Models;

var authenticationApiClient = new AuthenticationApiClient(new Uri(new Uri("https://YOUR_AUTH0_DOMAIN")));

var authenticationResponse = await authenticationApiClient.GetTokenAsync(new ResourceOwnerTokenRequest
{
    ClientId = "your client id",
    ClientSecret = 'your client secret",
    Realm = "Username-Password-Authentication", // the name of your DB connection
    Scope = "openid profile",
    Username = "user@company.com"
    Password = "password"
});
```

Also read this document for reference:
https://auth0.com/docs/api-auth/tutorials/adoption/password

**Comment by jerriep** [comment]
Also, I forgot to mention that when you call `GetTokenAsync` you will receive back an object which will contain an `AccessToken`. You will then subsequently need to call the `/userinfo` endpoint (https://auth0.com/docs/api/authentication#get-user-info) to get the actual user information

You can use the `GetUserInfoAsync` method of the `AuthenticationApiClient` to do that
